name: files.config.yaml.bak

# Which window class with it match against
# window_class: any(list(str()), str())

# dependencies: list(include('dependency', required=False))

keymaps:
    +dotfiles-rcfiles: $editor ~/dotfiles/rcfiles
    
    +yawhich-key-configs: ./yawhich-key ./layers/files.config.yawhich-key.yaml
    
