- command: $editor .
  name: +open-configs
- command: $terminal_hold git difftool origin/master
  name: +diff
- command: $terminal_hold git pull && xdg-open ./CHANGELOG.md
  name: +update
- command: $editor ./layers/$window_class.yaml
  name: +new-layer-for-current-window
